name: React CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x, 21.x] # Testing against LTS and current
        # Add more Node.js versions as needed
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Fix build folder permissions
      run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/portpolio/portpolio/build || true

    - name: Install dependencies
      run: npm ci # Use npm ci for clean installs

    - name: Set permissions for Nginx
      run: sudo chown -R www-data:www-data /home/ubuntu/actions-runner/_work/portpolio/portpolio/build

    - name: Run ESLint
      run: npm run lint # Assuming you have a "lint" script

    - name: Run Prettier
      run: npm run format:check # Assuming you have a "format:check" script

    - name: Run tests
      run: npm test -- --watchAll=false # Run tests and ensure no hanging

    - name: Build production build
      run: npm run build

    # Optional: Add steps for deployment (e.g., to Netlify, Vercel, S3)
    # Example for Netlify:
    # - name: Deploy to Netlify
    #   uses: netlify/actions/deploy@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
    #     deploy_preview: false
    #     publish_dir: './build'
    #   env:
    #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
