name: React CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x, 21.x]
        
    steps:
    # 🛠️ Fix permissions FIRST before checkout
    - name: Reset permissions before build
      run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/portpolio || true

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier
      run: npm run format:check

    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Build production build
      run: npm run build

    # Optional: Give Nginx access to build
    - name: Set permissions for Nginx
      run: sudo chown -R www-data:www-data /home/ubuntu/actions-runner/_work/portpolio/portpolio/build
